# Generated by Django 3.0.4 on 2020-04-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clap',
            name='vclap',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='vcomment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='vlike',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
