# Generated by Django 3.0.4 on 2020-04-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank='False', default='default.png', max_length=10000000, upload_to='videos/'),
        ),
    ]
